application: sdzpinochle
module: default
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:

inbound_services:
- channel_presence

handlers:
- url: /cards
  static_dir: server/cards
- url: /js
  static_dir: server/js
- url: /
  static_files: server/index.html
  upload: server/index\.html
- url: /.*
  script: _go_app

