application: sdzpinochle
version:     3
runtime:     go
api_version: go1
module: default

inbound_services:
- channel_presence

handlers:
- url: /cards
  static_dir: cards
- url: /js
  static_dir: js
- url: /
  static_files: index.html
  upload: index\.html
- url: /.*
  script: _go_app
